# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 10:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_auto_20160825_0942'),
    ]

    operations = [
        migrations.CreateModel(
            name='content_media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='blog_img')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='blog_img'),
        ),
        migrations.AddField(
            model_name='content_media',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.post'),
        ),
    ]
