# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_auto_20160825_1007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content_media',
            options={'verbose_name_plural': 'Resim Ekle'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name_plural': 'Blog Yaz'},
        ),
        migrations.AddField(
            model_name='post',
            name='time',
            field=models.DateField(null=True),
        ),
    ]
