# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0007_post_category_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
