# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 11:05
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0008_post_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='url',
        ),
        migrations.AddField(
            model_name='post',
            name='seo_url',
            field=models.TextField(null=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
