# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0010_auto_20160825_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='category_icon',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='category_keywords',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
